---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dantediy/gh-argocd-k8s-pri.git
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.default.svc
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #     allowEmpty: false